### ISSUE TITLE
Nurse Scheduling Problem

### ISSUE THREAD

**Issue by ssakhavi** [Thinklab-SJTU/awesome-ml4co#21]
Hi 

Thanks for the brilliant and awesome paper list. 
Out of curiosity, which category would you think the "nurse scheduling problem" falls into?

It seems to be a "Binary Integer Program" and I haven't seen many papers on it (except [CaVE](https://arxiv.org/abs/2312.07718)).

What do you think?

**Comment by only-changer** [comment]
I think both Job Shop Scheduling Problem (JSSP) and Mixed Integer Programming (MIP) are ok.

**Comment by ssakhavi** [comment]
Thanks @only-changer
