### ISSUE TITLE
Request for adding some paper list

### ISSUE THREAD

**Issue by Junyoungpark** [Thinklab-SJTU/awesome-ml4co#3]
Hi, Thank you for providing a nice collection of `ml4co`.

If you don't mind, can I share some list of papers that tackle `co` w/ RL?
- ScheduleNet: Learn to solve multi-agent scheduling problems with reinforcement learning
It tackles JSP and multiple agent extension of TSP (i.e. mTSP)
- Learning to schedule job-shop problems: representation and policy learning using graph neural network and reinforcement learning
It tackles JSP

**Comment by rogerwwww** [comment]
Closing this issue because the PR https://github.com/Thinklab-SJTU/awesome-ml4co/pull/5 is merged. Thanks!
